create table PROPERTIES  (
	ID INT NOT NULL AUTO_INCREMENT,
	APPLICATION VARCHAR(100) NOT NULL,
	PROFILE VARCHAR(100) NOT NULL,
	LABEL VARCHAR(100) NOT NULL,
	PROP_KEY VARCHAR(1000) NOT NULL,
	PROP_VAL VARCHAR(200) NOT NULL
);